### ISSUE TITLE
How to apply timezone with query ?

### ISSUE THREAD

**Issue by chiragjanjmeratecocraft** [laracraft-tech/laravel-date-scopes#1]
I need to to fetch records for diffrent user , those having diffrent timezones , How can I pass timezone with an query to fetch correct results?

**Comment by Sairahcaz** [comment]
In Laravel by default, the `created_at` column has the type `timestamp`, it does not store timezone information by itself. It is stored as a Unix timestamp (the number of seconds since the Unix Epoch), which is timezone-agnostic. But timezone conversion is done at the application level, you should handle it in you business logic, not in the database.

Maybe this article can help you:
https://www.learn2torials.com/a/how-to-handle-time-zones-using-laravel

**Comment by chiragjanjmeratecocraft** [comment]
Hi @Sairahcaz thank you for your answer.

**Comment by Sairahcaz** [comment]
Hi @chiragjanjmeratecocraft I thought about it again, I guess I will support adding timezones to the methods. I'll do that maybe in the next few weeks...
